language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

osx_image: xcode7.3
sudo: true
dist: trusty

env:
  global:
    - ERT_SHOW_BACKTRACE=1
    - INSTALL_DIR="$(pwd)/install"
    - LD_LIBRARY_PATH="${INSTALL_DIR}/lib:${INSTALL_DIR}/lib64"
    - PYTHONPATH="${INSTALL_DIR}/lib/python2.7/sist-packages:${INSTALL_DIR}/lib64/python2.7/sist-packages:$PYTHONPATH"
    - PYTHONPATH="${INSTALL_DIR}/lib/python2.7/dist-packages:${INSTALL_DIR}/lib64/python2.7/dist-packages:$PYTHONPATH"
  matrix:
    - PYTHON_VERSION=2.7 TEST_SUITE="-LE SLOW"  # Run all tests not labeled as slow
    - PYTHON_VERSION=2.7 TEST_SUITE="-L SLOW_1" # Run all tests labeled as SLOW in group 1
    - PYTHON_VERSION=2.7 TEST_SUITE="-L SLOW_2" # Run all tests labeled as SLOW in group 2
    - PYTHON_VERSION=2.7 TEST_SUITE=""          # TODO: Can be removed when libres is MacOS compliant
    - PYTHON_VERSION=3.6                        # Run all testsliant

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang
    # TODO: The excludes below should be removed after MacOS is supported
    - os: linux
      env: PYTHON_VERSION=2.7 TEST_SUITE=""
    - os: osx
      env: PYTHON_VERSION=2.7 TEST_SUITE="-LE SLOW"
    - os: osx
      env: PYTHON_VERSION=2.7 TEST_SUITE="-L SLOW_1"
    - os: osx
      env: PYTHON_VERSION=2.7 TEST_SUITE="-L SLOW_2"


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
      - sourceline: 'ppa:opm/ppa'
    packages:
      - libopm-simulators
      - liblapack-dev
      - valgrind
      - gcc-4.8
      - g++-4.8
      - clang
      - cmake
      - cmake-data

install:
  - if [[ "$CC" == "gcc" ]]; then export CXX="g++-4.8"; fi
  - sudo pip install --upgrade -r requirements.txt

before_script:
  # For now we have to make install libecl.
  # Remove when it's possible to pip install
  - git clone https://github.com/equinor/libecl
  - pushd libecl
  - sudo pip install -r requirements.txt
  - mkdir build
  - pushd build
  - cmake .. -DENABLE_PYTHON=ON
             -DBUILD_APPLICATIONS=ON
             -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR
             -DCMAKE_PREFIX_PATH=$INSTALL_DIR
             -DERT_USE_OPENMP=ON
             -DCMAKE_F_CLAGS='-Werror=all'
             -DCMAKE_CXX_FLAGS='-Werror -Wno-unused-result'
  - make
  - make install
  - popd;popd

script:
  - mkdir build
  - pushd build
  - cmake .. -DBUILD_TESTS=ON
             -DENABLE_PYTHON=ON
             -DBUILD_APPLICATIONS=ON
             -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR
             -DCMAKE_PREFIX_PATH=$INSTALL_DIR
             -DERT_USE_OPENMP=ON
             -DCMAKE_F_CLAGS='-Werror=all'
             -DCMAKE_CXX_FLAGS='-Werror -Wno-unused-result'
  - make
  - make install
  - set -e; python -c "import res"; set +e
  - ctest --output-on-failure $TEST_SUITE

